### ISSUE TITLE
texinfo dependency is missing

### ISSUE THREAD

**Issue by Ninjapouet** [OCamlPro/gnucobol#121] opened 2023-10-26 09:43 UTC
`./configure` tells all is ok and `make` gives:
```sh
make[3]: Entering directory '/home/julius/ocp/gnucobol/doc'
Updating ./version.texi
restore=: && backupdir=".am$$" && \
am__cwd=`pwd` && CDPATH="${ZSH_VERSION+.}:" && cd . && \
rm -rf $backupdir && mkdir $backupdir && \
if (/bin/bash /home/julius/ocp/gnucobol/build_aux/missing makeinfo --version) >/dev/null 2>&1; then \
  for f in gnucobol.info gnucobol.info-[0-9] gnucobol.info-[0-9][0-9] gnucobol.i[0-9] gnucobol.i[0-9][0-9]; do \
    if test -f $f; then mv $f $backupdir; restore=mv; else :; fi; \
  done; \
else :; fi && \
cd "$am__cwd"; \
if /bin/bash /home/julius/ocp/gnucobol/build_aux/missing makeinfo   -I . \
 -o gnucobol.info gnucobol.texi; \
then \
  rc=0; \
  CDPATH="${ZSH_VERSION+.}:" && cd .; \
else \
  rc=$?; \
  CDPATH="${ZSH_VERSION+.}:" && cd . && \
  $restore $backupdir/* `echo "./gnucobol.info" | sed 's|[^/]*$||'`; \
fi; \
rm -rf $backupdir; exit $rc
/home/julius/ocp/gnucobol/build_aux/missing: line 81: makeinfo: command not found
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
         You might want to install the Texinfo package:
         <https://www.gnu.org/software/texinfo/>
         The spurious makeinfo call might also be the consequence of
         using a buggy 'make' (AIX, DU, IRIX), in which case you might
         want to install GNU make:
         <https://www.gnu.org/software/make/>
```

**Comment by GitMensch** [comment] 2023-10-26 14:07
all noted in HACKING, duplicate of #119

**Closed by GitMensch** 2023-10-26 14:07 UTC
