### ISSUE TITLE
flex dependency is missing

### ISSUE THREAD

**Issue by Ninjapouet** [OCamlPro/gnucobol#120] opened 2023-10-26 09:38 UTC
`./configure` tells all is ok but `make` gives:
```sh
make[3]: Entering directory '/home/julius/ocp/gnucobol/cobc'
gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I../lib -I../lib    -O2 -pipe -finline-functions -fsigned-char -Wall -Wwrite-strings -Wmissing-prototypes -Wno-format-y2k -MT cobc.o -MD -MP -MF .deps/cobc.Tpo -c -o cobc.o cobc.c
mv -f .deps/cobc.Tpo .deps/cobc.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I../lib -I../lib    -O2 -pipe -finline-functions -fsigned-char -Wall -Wwrite-strings -Wmissing-prototypes -Wno-format-y2k -MT ppparse.o -MD -MP -MF .deps/ppparse.Tpo -c -o ppparse.o ppparse.c
mv -f .deps/ppparse.Tpo .deps/ppparse.Po
LC_CTYPE=C /bin/bash /home/julius/ocp/gnucobol/build_aux/missing flex -opplex.c pplex.l
/home/julius/ocp/gnucobol/build_aux/missing: line 81: flex: command not found
WARNING: 'flex' is missing on your system.
         You should only need it if you modified a '.l' file.
         You may want to install the Fast Lexical Analyzer package:
         <https://github.com/westes/flex>
make[3]: *** [Makefile:1066: pplex.c] Error 127
```

**Comment by GitMensch** [comment] 2023-10-26 14:06
all noted in HACKING, duplicate of #119

**Closed** 2023-10-26 14:06 UTC
